services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GolemAi\Microservice\RabbitMQ\DataTransformer\DataTransformerInterface: '@GolemAi\Microservice\RabbitMQ\DataTransformer\JsonTransformer'
    GolemAi\Microservice\RabbitMQ\DataTransformer\JsonTransformer:
        arguments:
        - '@serializer'
    GolemAi\Microservice\RabbitMQ\DataFormatter\DataFormatterInterface: '@GolemAi\Microservice\RabbitMQ\DataFormatter\DataFormatter'
    GolemAi\Microservice\RabbitMQ\DataFormatter\DataFormatter:
        arguments:
            - '@GolemAi\Microservice\RabbitMQ\DataTransformer\DataTransformerInterface'